<template>

   <div class="galerieContainer">

       <div class="photoContainer">
                
        <vueper-slides :slide-ratio="1 / 2" fixed-height="600px">
        <vueper-slide v-for="(slide, i) in slides" :key="i" :image="slide.image" />
        </vueper-slides>

       </div>

   </div>

</template>


<script>

    import { VueperSlides, VueperSlide } from 'vueperslides'
    import 'vueperslides/dist/vueperslides.css'

    export default {
    components: { VueperSlides, VueperSlide },
  
    data: () => ({
        slides: [
            { image: require('./../../assets/photos/künstler/künstler1.jpg') },
            { image: require('./../../assets/photos/künstler/künstler2.jpg') },
            { image: require('./../../assets/photos/künstler/künstler3.jpg') },
            { image: require('./../../assets/photos/künstler/künstler4.png') },
            { image: require('./../../assets/photos/künstler/künstler5.png') },
            { image: require('./../../assets/photos/künstler/künstler6.png') },
            { image: require('./../../assets/photos/künstler/künstler7.png') },
            { image: require('./../../assets/photos/künstler/künstler8.jpg') },
            { image: require('./../../assets/photos/künstler/künstler9.jpg') },
            { image: require('./../../assets/photos/künstler/künstler10.jpg') },
            { image: require('./../../assets/photos/künstler/künstler11.jpg') },
            { image: require('./../../assets/photos/künstler/künstler12.jpg') },
            { image: require('./../../assets/photos/künstler/künstler13.jpg') },
            { image: require('./../../assets/photos/künstler/künstler14.jpg') },
            { image: require('./../../assets/photos/künstler/künstler15.jpg') },
            { image: require('./../../assets/photos/künstler/künstler17.jpg') },
            { image: require('./../../assets/photos/künstler/künstler18.jpg') },
            { image: require('./../../assets/photos/künstler/künstler19.jpg') },
            { image: require('./../../assets/photos/künstler/künstler20.jpg') },
            { image: require('./../../assets/photos/künstler/künstler21.jpg') },
            { image: require('./../../assets/photos/künstler/künstler22.jpg') },
            { image: require('./../../assets/photos/künstler/künstler23.jpg') },
            { image: require('./../../assets/photos/künstler/künstler24.jpg') },
            { image: require('./../../assets/photos/künstler/künstler25.jpg') },
            { image: require('./../../assets/photos/künstler/künstler26.jpg') },
            { image: require('./../../assets/photos/künstler/künstler27.jpg') },
            { image: require('./../../assets/photos/künstler/künstler28.jpg') },
            { image: require('./../../assets/photos/künstler/künstler29.jpg') },
            { image: require('./../../assets/photos/künstler/künstler30.jpg') },
            { image: require('./../../assets/photos/künstler/künstler31.jpg') },
            { image: require('./../../assets/photos/künstler/künstler32.jpg') },
            { image: require('./../../assets/photos/künstler/künstler33.jpg') },
            { image: require('./../../assets/photos/künstler/künstler34.jpg') },
            { image: require('./../../assets/photos/künstler/künstler35.jpg') },
            { image: require('./../../assets/photos/künstler/künstler36.jpg') },
            { image: require('./../../assets/photos/künstler/künstler37.jpg') },
            { image: require('./../../assets/photos/künstler/künstler38.jpg') },
            { image: require('./../../assets/photos/künstler/künstler39.jpg') },
            { image: require('./../../assets/photos/künstler/künstler40.jpg') },
            { image: require('./../../assets/photos/künstler/künstler41.jpg') },
            { image: require('./../../assets/photos/künstler/künstler42.jpg') },
            { image: require('./../../assets/photos/künstler/künstler43.jpg') },
            { image: require('./../../assets/photos/künstler/künstler44.jpg') },
            { image: require('./../../assets/photos/künstler/künstler45.jpg') },
            { image: require('./../../assets/photos/künstler/künstler46.jpg') },
            { image: require('./../../assets/photos/künstler/künstler47.jpg') },
            { image: require('./../../assets/photos/künstler/künstler48.jpg') },
            { image: require('./../../assets/photos/künstler/künstler49.jpg') },
            { image: require('./../../assets/photos/künstler/künstler50.jpg') },
            { image: require('./../../assets/photos/künstler/künstler50.jpg') },
            { image: require('./../../assets/photos/künstler/künstler51.jpg') },
            { image: require('./../../assets/photos/künstler/künstler52.jpg') },
            { image: require('./../../assets/photos/künstler/künstler53.jpg') },
            { image: require('./../../assets/photos/künstler/künstler54.jpg') },
            { image: require('./../../assets/photos/künstler/künstler55.jpg') },
            { image: require('./../../assets/photos/künstler/künstler56.jpg') },
            { image: require('./../../assets/photos/künstler/künstler57.jpg') },
            { image: require('./../../assets/photos/künstler/künstler58.jpg') },
            { image: require('./../../assets/photos/künstler/künstler59.jpg') },
            { image: require('./../../assets/photos/künstler/künstler60.jpg') },
            { image: require('./../../assets/photos/künstler/künstler61.jpg') },
            { image: require('./../../assets/photos/künstler/künstler62.jpg') },
            { image: require('./../../assets/photos/künstler/künstler63.jpg') },
            { image: require('./../../assets/photos/künstler/künstler64.jpg') },
            { image: require('./../../assets/photos/künstler/künstler65.jpg') },
            { image: require('./../../assets/photos/künstler/künstler66.jpg') },
            { image: require('./../../assets/photos/künstler/künstler67.jpg') },
            { image: require('./../../assets/photos/künstler/künstler68.jpg') },
            { image: require('./../../assets/photos/künstler/künstler69.jpg') },
            { image: require('./../../assets/photos/künstler/künstler71.jpg') },
            { image: require('./../../assets/photos/künstler/künstler72.jpg') },
            { image: require('./../../assets/photos/künstler/künstler73.jpg') },
            { image: require('./../../assets/photos/künstler/künstler74.jpg') },
            { image: require('./../../assets/photos/künstler/künstler75.jpg') },
            { image: require('./../../assets/photos/künstler/künstler76.jpg') },
            { image: require('./../../assets/photos/künstler/künstler77.jpg') },
            { image: require('./../../assets/photos/künstler/künstler78.jpg') },
            { image: require('./../../assets/photos/künstler/künstler79.jpg') },
            { image: require('./../../assets/photos/künstler/künstler80.jpg') },
            { image: require('./../../assets/photos/künstler/künstler81.jpg') },
            { image: require('./../../assets/photos/künstler/künstler82.jpg') },
            { image: require('./../../assets/photos/künstler/künstler83.jpg') },
            { image: require('./../../assets/photos/künstler/künstler84.jpg') },
            { image: require('./../../assets/photos/künstler/künstler85.jpg') },
            { image: require('./../../assets/photos/künstler/künstler86.jpg') },
            { image: require('./../../assets/photos/künstler/künstler87.jpg') },
            { image: require('./../../assets/photos/künstler/künstler88.jpg') },
            { image: require('./../../assets/photos/künstler/künstler89.jpg') },
            { image: require('./../../assets/photos/künstler/künstler91.jpg') },
            { image: require('./../../assets/photos/künstler/künstler92.jpg') },
            { image: require('./../../assets/photos/künstler/künstler93.jpg') },
            { image: require('./../../assets/photos/künstler/künstler94.jpg') },
            { image: require('./../../assets/photos/künstler/künstler95.jpg') },
            { image: require('./../../assets/photos/künstler/künstler96.jpg') },
            { image: require('./../../assets/photos/künstler/künstler97.jpg') },
            { image: require('./../../assets/photos/künstler/künstler98.jpg') },
            { image: require('./../../assets/photos/künstler/künstler99.jpg') },
            { image: require('./../../assets/photos/künstler/künstler100.jpg') },
            { image: require('./../../assets/photos/künstler/künstler101.jpg') },
            { image: require('./../../assets/photos/künstler/künstler102.jpg') },
            { image: require('./../../assets/photos/künstler/künstler103.jpg') },
            { image: require('./../../assets/photos/künstler/künstler104.jpg') },
            { image: require('./../../assets/photos/künstler/künstler105.jpg') },
            { image: require('./../../assets/photos/künstler/künstler106.jpg') },
            { image: require('./../../assets/photos/künstler/künstler107.jpg') },
            { image: require('./../../assets/photos/künstler/künstler108.jpg') },
            { image: require('./../../assets/photos/künstler/künstler109.jpg') },
            { image: require('./../../assets/photos/künstler/künstler112.jpg') },
            { image: require('./../../assets/photos/künstler/künstler113.jpg') },
            { image: require('./../../assets/photos/künstler/künstler114.jpg') },
            { image: require('./../../assets/photos/künstler/künstler115.jpg') },
            { image: require('./../../assets/photos/künstler/künstler116.jpg') },
            { image: require('./../../assets/photos/künstler/künstler117.jpg') },
            { image: require('./../../assets/photos/künstler/künstler118.jpg') },
            { image: require('./../../assets/photos/künstler/künstler119.jpg') },
            { image: require('./../../assets/photos/künstler/künstler120.jpg') },
            { image: require('./../../assets/photos/künstler/künstler121.jpg') },
            { image: require('./../../assets/photos/künstler/künstler122.jpg') },
            { image: require('./../../assets/photos/künstler/künstler123.jpg') },
            { image: require('./../../assets/photos/künstler/künstler124.jpg') },
            { image: require('./../../assets/photos/künstler/künstler125.jpg') },
            { image: require('./../../assets/photos/künstler/künstler126.jpg') },
            { image: require('./../../assets/photos/künstler/künstler127.jpg') },
            { image: require('./../../assets/photos/künstler/künstler128.jpg') },
            { image: require('./../../assets/photos/künstler/künstler129.jpg') },
            { image: require('./../../assets/photos/künstler/künstler130.jpg') },
            { image: require('./../../assets/photos/künstler/künstler131.jpg') },
            { image: require('./../../assets/photos/künstler/künstler132.jpg') },
            { image: require('./../../assets/photos/künstler/künstler133.jpg') },
            { image: require('./../../assets/photos/künstler/künstler134.jpg') },
            { image: require('./../../assets/photos/künstler/künstler135.jpg') },
            { image: require('./../../assets/photos/künstler/künstler136.jpg') },
            { image: require('./../../assets/photos/künstler/künstler137.jpg') },
            { image: require('./../../assets/photos/künstler/künstler138.jpg') },
            { image: require('./../../assets/photos/künstler/künstler139.jpg') },
            { image: require('./../../assets/photos/künstler/künstler141.jpg') },
            { image: require('./../../assets/photos/künstler/künstler142.jpg') },
            { image: require('./../../assets/photos/künstler/künstler143.jpg') },
            { image: require('./../../assets/photos/künstler/künstler144.jpg') },
            { image: require('./../../assets/photos/künstler/künstler145.jpg') },
            { image: require('./../../assets/photos/künstler/künstler146.jpg') },
            { image: require('./../../assets/photos/künstler/künstler147.jpg') },
            { image: require('./../../assets/photos/künstler/künstler148.jpg') },
            { image: require('./../../assets/photos/künstler/künstler149.jpg') },
            { image: require('./../../assets/photos/künstler/künstler150.jpg') },
            { image: require('./../../assets/photos/künstler/künstler151.jpg') },
            { image: require('./../../assets/photos/künstler/künstler152.jpg') },
            { image: require('./../../assets/photos/künstler/künstler153.jpg') },
            { image: require('./../../assets/photos/künstler/künstler154.jpg') },
            { image: require('./../../assets/photos/künstler/künstler155.jpg') },
            { image: require('./../../assets/photos/künstler/künstler156.jpg') },
            { image: require('./../../assets/photos/künstler/künstler157.jpg') },
            { image: require('./../../assets/photos/künstler/künstler158.jpg') },
            { image: require('./../../assets/photos/künstler/künstler159.jpg') },
            { image: require('./../../assets/photos/künstler/künstler160.jpg') },
            { image: require('./../../assets/photos/künstler/künstler161.jpg') },
            { image: require('./../../assets/photos/künstler/künstler162.jpg') },
            { image: require('./../../assets/photos/künstler/künstler163.jpg') },
            { image: require('./../../assets/photos/künstler/künstler164.jpg') },
            { image: require('./../../assets/photos/künstler/künstler165.jpg') },
            { image: require('./../../assets/photos/künstler/künstler166.jpg') },
            { image: require('./../../assets/photos/künstler/künstler167.jpg') },
            { image: require('./../../assets/photos/künstler/künstler168.jpg') },
            { image: require('./../../assets/photos/künstler/künstler169.jpg') },
            { image: require('./../../assets/photos/künstler/künstler170.jpg') },
            { image: require('./../../assets/photos/künstler/künstler171.jpg') },
            { image: require('./../../assets/photos/künstler/künstler172.jpg') },
            { image: require('./../../assets/photos/künstler/künstler173.jpg') },
            { image: require('./../../assets/photos/künstler/künstler174.jpg') },
            { image: require('./../../assets/photos/künstler/künstler175.jpg') },
            { image: require('./../../assets/photos/künstler/künstler176.jpg') },
            { image: require('./../../assets/photos/künstler/künstler177.jpg') },
            { image: require('./../../assets/photos/künstler/künstler178.jpg') },
            { image: require('./../../assets/photos/künstler/künstler179.jpg') },
            { image: require('./../../assets/photos/künstler/künstler180.jpg') },
            { image: require('./../../assets/photos/künstler/künstler181.jpg') },
            { image: require('./../../assets/photos/künstler/künstler182.jpg') },
            { image: require('./../../assets/photos/künstler/künstler183.jpg') },
            { image: require('./../../assets/photos/künstler/künstler184.jpg') },
            { image: require('./../../assets/photos/künstler/künstler185.jpg') },
            { image: require('./../../assets/photos/künstler/künstler186.jpg') },
            { image: require('./../../assets/photos/künstler/künstler187.jpg') },
            { image: require('./../../assets/photos/künstler/künstler188.jpg') },
            { image: require('./../../assets/photos/künstler/künstler189.jpg') },
            { image: require('./../../assets/photos/künstler/künstler190.jpg') },
            { image: require('./../../assets/photos/künstler/künstler191.jpg') },
            { image: require('./../../assets/photos/künstler/künstler192.jpg') },
            { image: require('./../../assets/photos/künstler/künstler193.jpg') },
            { image: require('./../../assets/photos/künstler/künstler194.jpg') },
            { image: require('./../../assets/photos/künstler/künstler195.jpg') },
            { image: require('./../../assets/photos/künstler/künstler196.jpg') },
            { image: require('./../../assets/photos/künstler/künstler197.jpg') },
            { image: require('./../../assets/photos/künstler/künstler198.jpg') },
            { image: require('./../../assets/photos/künstler/künstler199.jpg') },
            { image: require('./../../assets/photos/künstler/künstler201.jpg') },
            { image: require('./../../assets/photos/künstler/künstler202.jpg') },
            { image: require('./../../assets/photos/künstler/künstler203.jpg') },
            { image: require('./../../assets/photos/künstler/künstler204.jpg') },
            { image: require('./../../assets/photos/künstler/künstler205.jpg') },
            { image: require('./../../assets/photos/künstler/künstler206.jpg') },
            { image: require('./../../assets/photos/künstler/künstler207.jpg') },
            { image: require('./../../assets/photos/künstler/künstler208.jpg') },
            { image: require('./../../assets/photos/künstler/künstler209.jpg') },
            { image: require('./../../assets/photos/künstler/künstler210.jpg') },
            { image: require('./../../assets/photos/künstler/künstler211.jpg') },
            { image: require('./../../assets/photos/künstler/künstler212.jpg') },
            { image: require('./../../assets/photos/künstler/künstler213.jpg') },
            { image: require('./../../assets/photos/künstler/künstler214.jpg') },
            { image: require('./../../assets/photos/künstler/künstler215.jpg') },
            { image: require('./../../assets/photos/künstler/künstler216.jpg') },
            { image: require('./../../assets/photos/künstler/künstler217.jpg') },
            { image: require('./../../assets/photos/künstler/künstler218.jpg') },
            { image: require('./../../assets/photos/künstler/künstler219.jpg') },
            { image: require('./../../assets/photos/künstler/künstler220.jpg') },
            { image: require('./../../assets/photos/künstler/künstler221.jpg') },
            { image: require('./../../assets/photos/künstler/künstler222.jpg') },
            { image: require('./../../assets/photos/künstler/künstler223.jpg') },
            { image: require('./../../assets/photos/künstler/künstler224.jpg') },
            { image: require('./../../assets/photos/künstler/künstler225.jpg') },
            { image: require('./../../assets/photos/künstler/künstler226.jpg') },
            { image: require('./../../assets/photos/künstler/künstler227.jpg') },
            { image: require('./../../assets/photos/künstler/künstler228.jpg') },
            { image: require('./../../assets/photos/künstler/künstler229.jpg') },
            { image: require('./../../assets/photos/künstler/künstler230.jpg') },
            { image: require('./../../assets/photos/künstler/künstler231.jpg') },
            { image: require('./../../assets/photos/künstler/künstler232.jpg') },
            { image: require('./../../assets/photos/künstler/künstler233.jpg') },
            { image: require('./../../assets/photos/künstler/künstler234.jpg') },
            { image: require('./../../assets/photos/künstler/künstler235.jpg') },
            { image: require('./../../assets/photos/künstler/künstler236.jpg') },
            { image: require('./../../assets/photos/künstler/künstler237.jpg') },
            { image: require('./../../assets/photos/künstler/künstler238.jpg') },
            { image: require('./../../assets/photos/künstler/künstler239.jpg') },
            { image: require('./../../assets/photos/künstler/künstler240.jpg') },
            { image: require('./../../assets/photos/künstler/künstler241.jpg') },
            { image: require('./../../assets/photos/künstler/künstler242.jpg') },
            { image: require('./../../assets/photos/künstler/künstler243.jpg') },
            { image: require('./../../assets/photos/künstler/künstler244.jpg') },
            { image: require('./../../assets/photos/künstler/künstler245.jpg') },
            { image: require('./../../assets/photos/künstler/künstler246.jpg') },
            { image: require('./../../assets/photos/künstler/künstler247.jpg') },
            { image: require('./../../assets/photos/künstler/künstler248.jpg') },
            { image: require('./../../assets/photos/künstler/künstler249.jpg') },
            { image: require('./../../assets/photos/künstler/künstler250.jpg') },
            { image: require('./../../assets/photos/künstler/künstler251.jpg') },
            { image: require('./../../assets/photos/künstler/künstler252.jpg') },
            { image: require('./../../assets/photos/künstler/künstler253.jpg') },
            { image: require('./../../assets/photos/künstler/künstler254.jpg') },
            { image: require('./../../assets/photos/künstler/künstler255.jpg') },
        ]
        })

    }

</script>



<style>

     @import './../../assets/styles/galerie.css';

</style>
