<template>

    <div class="galerieContainer">

        <div id="app" class="photoContainer">
            <img class="image" v-for="(image, i) in images" :src="image" :key="i" @click="index = i">
            <client-only placeholder="Loading...">
                <VueGallerySlideshow :images="images" :index="index" @close="index = null" />
            </client-only>
        </div>

    </div>

</template>


<script>

    import VueGallerySlideshow from 'vue-gallery-slideshow';

    export default {
    components: { VueGallerySlideshow },
  
    data: () => ({
        images: [
            require('./../../assets/photos/künstler/künstler1.jpg') ,
            require('./../../assets/photos/künstler/künstler2.jpg') ,
            require('./../../assets/photos/künstler/künstler3.jpg') ,
            require('./../../assets/photos/künstler/künstler4.png') ,
            require('./../../assets/photos/künstler/künstler5.png') ,
            require('./../../assets/photos/künstler/künstler6.png') ,
            require('./../../assets/photos/künstler/künstler7.png') ,
            require('./../../assets/photos/künstler/künstler8.jpg') ,
            require('./../../assets/photos/künstler/künstler9.jpg') ,
            require('./../../assets/photos/künstler/künstler10.jpg') ,
            require('./../../assets/photos/künstler/künstler11.jpg') ,
            require('./../../assets/photos/künstler/künstler12.jpg') ,
            require('./../../assets/photos/künstler/künstler13.jpg') ,
            require('./../../assets/photos/künstler/künstler14.jpg') ,
            require('./../../assets/photos/künstler/künstler15.jpg') ,
            require('./../../assets/photos/künstler/künstler17.jpg') ,
            require('./../../assets/photos/künstler/künstler18.jpg') ,
            require('./../../assets/photos/künstler/künstler19.jpg') ,
            require('./../../assets/photos/künstler/künstler20.jpg') ,
            require('./../../assets/photos/künstler/künstler21.jpg') ,
            require('./../../assets/photos/künstler/künstler22.jpg') ,
            require('./../../assets/photos/künstler/künstler23.jpg') ,
            require('./../../assets/photos/künstler/künstler24.jpg') ,
            require('./../../assets/photos/künstler/künstler25.jpg') ,
            require('./../../assets/photos/künstler/künstler26.jpg') ,
            require('./../../assets/photos/künstler/künstler27.jpg') ,
            require('./../../assets/photos/künstler/künstler28.jpg') ,
            require('./../../assets/photos/künstler/künstler29.jpg') ,
            require('./../../assets/photos/künstler/künstler30.jpg') ,
            require('./../../assets/photos/künstler/künstler31.jpg') ,
            require('./../../assets/photos/künstler/künstler32.jpg') ,
            require('./../../assets/photos/künstler/künstler33.jpg') ,
            require('./../../assets/photos/künstler/künstler34.jpg') ,
            require('./../../assets/photos/künstler/künstler35.jpg') ,
            require('./../../assets/photos/künstler/künstler36.jpg') ,
            require('./../../assets/photos/künstler/künstler37.jpg') ,
            require('./../../assets/photos/künstler/künstler38.jpg') ,
            require('./../../assets/photos/künstler/künstler39.jpg') ,
            require('./../../assets/photos/künstler/künstler40.jpg') ,
            require('./../../assets/photos/künstler/künstler41.jpg') ,
            require('./../../assets/photos/künstler/künstler42.jpg') ,
            require('./../../assets/photos/künstler/künstler43.jpg') ,
            require('./../../assets/photos/künstler/künstler44.jpg') ,
            require('./../../assets/photos/künstler/künstler45.jpg') ,
            require('./../../assets/photos/künstler/künstler46.jpg') ,
            require('./../../assets/photos/künstler/künstler47.jpg') ,
            require('./../../assets/photos/künstler/künstler48.jpg') ,
            require('./../../assets/photos/künstler/künstler49.jpg') ,
            require('./../../assets/photos/künstler/künstler50.jpg') ,
            require('./../../assets/photos/künstler/künstler50.jpg') ,
            require('./../../assets/photos/künstler/künstler51.jpg') ,
            require('./../../assets/photos/künstler/künstler52.jpg') ,
            require('./../../assets/photos/künstler/künstler53.jpg') ,
            require('./../../assets/photos/künstler/künstler54.jpg') ,
            require('./../../assets/photos/künstler/künstler55.jpg') ,
            require('./../../assets/photos/künstler/künstler56.jpg') ,
            require('./../../assets/photos/künstler/künstler57.jpg') ,
            require('./../../assets/photos/künstler/künstler58.jpg') ,
            require('./../../assets/photos/künstler/künstler59.jpg') ,
            require('./../../assets/photos/künstler/künstler60.jpg') ,
            require('./../../assets/photos/künstler/künstler61.jpg') ,
            require('./../../assets/photos/künstler/künstler62.jpg') ,
            require('./../../assets/photos/künstler/künstler63.jpg') ,
            require('./../../assets/photos/künstler/künstler64.jpg') ,
            require('./../../assets/photos/künstler/künstler65.jpg') ,
            require('./../../assets/photos/künstler/künstler66.jpg') ,
            require('./../../assets/photos/künstler/künstler67.jpg') ,
            require('./../../assets/photos/künstler/künstler68.jpg') ,
            require('./../../assets/photos/künstler/künstler69.jpg') ,
            require('./../../assets/photos/künstler/künstler71.jpg') ,
            require('./../../assets/photos/künstler/künstler72.jpg') ,
            require('./../../assets/photos/künstler/künstler73.jpg') ,
            require('./../../assets/photos/künstler/künstler74.jpg') ,
            require('./../../assets/photos/künstler/künstler75.jpg') ,
            require('./../../assets/photos/künstler/künstler76.jpg') ,
            require('./../../assets/photos/künstler/künstler77.jpg') ,
            require('./../../assets/photos/künstler/künstler78.jpg') ,
            require('./../../assets/photos/künstler/künstler79.jpg') ,
            require('./../../assets/photos/künstler/künstler80.jpg') ,
            require('./../../assets/photos/künstler/künstler81.jpg') ,
            require('./../../assets/photos/künstler/künstler82.jpg') ,
            require('./../../assets/photos/künstler/künstler83.jpg') ,
            require('./../../assets/photos/künstler/künstler84.jpg') ,
            require('./../../assets/photos/künstler/künstler85.jpg') ,
            require('./../../assets/photos/künstler/künstler86.jpg') ,
            require('./../../assets/photos/künstler/künstler87.jpg') ,
            require('./../../assets/photos/künstler/künstler88.jpg') ,
            require('./../../assets/photos/künstler/künstler89.jpg') ,
            require('./../../assets/photos/künstler/künstler91.jpg') ,
            require('./../../assets/photos/künstler/künstler92.jpg') ,
            require('./../../assets/photos/künstler/künstler93.jpg') ,
            require('./../../assets/photos/künstler/künstler94.jpg') ,
            require('./../../assets/photos/künstler/künstler95.jpg') ,
            require('./../../assets/photos/künstler/künstler96.jpg') ,
            require('./../../assets/photos/künstler/künstler97.jpg') ,
            require('./../../assets/photos/künstler/künstler98.jpg') ,
            require('./../../assets/photos/künstler/künstler99.jpg') ,
            require('./../../assets/photos/künstler/künstler100.jpg') ,
            require('./../../assets/photos/künstler/künstler101.jpg') ,
            require('./../../assets/photos/künstler/künstler102.jpg') ,
            require('./../../assets/photos/künstler/künstler103.jpg') ,
            require('./../../assets/photos/künstler/künstler104.jpg') ,
            require('./../../assets/photos/künstler/künstler105.jpg') ,
            require('./../../assets/photos/künstler/künstler106.jpg') ,
            require('./../../assets/photos/künstler/künstler107.jpg') ,
            require('./../../assets/photos/künstler/künstler108.jpg') ,
            require('./../../assets/photos/künstler/künstler109.jpg') ,
            require('./../../assets/photos/künstler/künstler112.jpg') ,
            require('./../../assets/photos/künstler/künstler113.jpg') ,
            require('./../../assets/photos/künstler/künstler114.jpg') ,
            require('./../../assets/photos/künstler/künstler115.jpg') ,
            require('./../../assets/photos/künstler/künstler116.jpg') ,
            require('./../../assets/photos/künstler/künstler117.jpg') ,
            require('./../../assets/photos/künstler/künstler118.jpg') ,
            require('./../../assets/photos/künstler/künstler119.jpg') ,
            require('./../../assets/photos/künstler/künstler120.jpg') ,
            require('./../../assets/photos/künstler/künstler121.jpg') ,
            require('./../../assets/photos/künstler/künstler122.jpg') ,
            require('./../../assets/photos/künstler/künstler123.jpg') ,
            require('./../../assets/photos/künstler/künstler124.jpg') ,
            require('./../../assets/photos/künstler/künstler125.jpg') ,
            require('./../../assets/photos/künstler/künstler126.jpg') ,
            require('./../../assets/photos/künstler/künstler127.jpg') ,
            require('./../../assets/photos/künstler/künstler128.jpg') ,
            require('./../../assets/photos/künstler/künstler129.jpg') ,
            require('./../../assets/photos/künstler/künstler130.jpg') ,
            require('./../../assets/photos/künstler/künstler131.jpg') ,
            require('./../../assets/photos/künstler/künstler132.jpg') ,
            require('./../../assets/photos/künstler/künstler133.jpg') ,
            require('./../../assets/photos/künstler/künstler134.jpg') ,
            require('./../../assets/photos/künstler/künstler135.jpg') ,
            require('./../../assets/photos/künstler/künstler136.jpg') ,
            require('./../../assets/photos/künstler/künstler137.jpg') ,
            require('./../../assets/photos/künstler/künstler138.jpg') ,
            require('./../../assets/photos/künstler/künstler139.jpg') ,
            require('./../../assets/photos/künstler/künstler141.jpg') ,
            require('./../../assets/photos/künstler/künstler142.jpg') ,
            require('./../../assets/photos/künstler/künstler143.jpg') ,
            require('./../../assets/photos/künstler/künstler144.jpg') ,
            require('./../../assets/photos/künstler/künstler145.jpg') ,
            require('./../../assets/photos/künstler/künstler146.jpg') ,
            require('./../../assets/photos/künstler/künstler147.jpg') ,
            require('./../../assets/photos/künstler/künstler148.jpg') ,
            require('./../../assets/photos/künstler/künstler149.jpg') ,
            require('./../../assets/photos/künstler/künstler150.jpg') ,
            require('./../../assets/photos/künstler/künstler151.jpg') ,
            require('./../../assets/photos/künstler/künstler152.jpg') ,
            require('./../../assets/photos/künstler/künstler153.jpg') ,
            require('./../../assets/photos/künstler/künstler154.jpg') ,
            require('./../../assets/photos/künstler/künstler155.jpg') ,
            require('./../../assets/photos/künstler/künstler156.jpg') ,
            require('./../../assets/photos/künstler/künstler157.jpg') ,
            require('./../../assets/photos/künstler/künstler158.jpg') ,
            require('./../../assets/photos/künstler/künstler159.jpg') ,
            require('./../../assets/photos/künstler/künstler160.jpg') ,
            require('./../../assets/photos/künstler/künstler161.jpg') ,
            require('./../../assets/photos/künstler/künstler162.jpg') ,
            require('./../../assets/photos/künstler/künstler163.jpg') ,
            require('./../../assets/photos/künstler/künstler164.jpg') ,
            require('./../../assets/photos/künstler/künstler165.jpg') ,
            require('./../../assets/photos/künstler/künstler166.jpg') ,
            require('./../../assets/photos/künstler/künstler167.jpg') ,
            require('./../../assets/photos/künstler/künstler168.jpg') ,
            require('./../../assets/photos/künstler/künstler169.jpg') ,
            require('./../../assets/photos/künstler/künstler170.jpg') ,
            require('./../../assets/photos/künstler/künstler171.jpg') ,
            require('./../../assets/photos/künstler/künstler172.jpg') ,
            require('./../../assets/photos/künstler/künstler173.jpg') ,
            require('./../../assets/photos/künstler/künstler174.jpg') ,
            require('./../../assets/photos/künstler/künstler175.jpg') ,
            require('./../../assets/photos/künstler/künstler176.jpg') ,
            require('./../../assets/photos/künstler/künstler177.jpg') ,
            require('./../../assets/photos/künstler/künstler178.jpg') ,
            require('./../../assets/photos/künstler/künstler179.jpg') ,
            require('./../../assets/photos/künstler/künstler180.jpg') ,
            require('./../../assets/photos/künstler/künstler181.jpg') ,
            require('./../../assets/photos/künstler/künstler182.jpg') ,
            require('./../../assets/photos/künstler/künstler183.jpg') ,
            require('./../../assets/photos/künstler/künstler184.jpg') ,
            require('./../../assets/photos/künstler/künstler185.jpg') ,
            require('./../../assets/photos/künstler/künstler186.jpg') ,
            require('./../../assets/photos/künstler/künstler187.jpg') ,
            require('./../../assets/photos/künstler/künstler188.jpg') ,
            require('./../../assets/photos/künstler/künstler189.jpg') ,
            require('./../../assets/photos/künstler/künstler190.jpg') ,
            require('./../../assets/photos/künstler/künstler191.jpg') ,
            require('./../../assets/photos/künstler/künstler192.jpg') ,
            require('./../../assets/photos/künstler/künstler193.jpg') ,
            require('./../../assets/photos/künstler/künstler194.jpg') ,
            require('./../../assets/photos/künstler/künstler195.jpg') ,
            require('./../../assets/photos/künstler/künstler196.jpg') ,
            require('./../../assets/photos/künstler/künstler197.jpg') ,
            require('./../../assets/photos/künstler/künstler198.jpg') ,
            require('./../../assets/photos/künstler/künstler199.jpg') ,
            require('./../../assets/photos/künstler/künstler201.jpg') ,
            require('./../../assets/photos/künstler/künstler202.jpg') ,
            require('./../../assets/photos/künstler/künstler203.jpg') ,
            require('./../../assets/photos/künstler/künstler204.jpg') ,
            require('./../../assets/photos/künstler/künstler205.jpg') ,
            require('./../../assets/photos/künstler/künstler206.jpg') ,
            require('./../../assets/photos/künstler/künstler207.jpg') ,
            require('./../../assets/photos/künstler/künstler208.jpg') ,
            require('./../../assets/photos/künstler/künstler209.jpg') ,
            require('./../../assets/photos/künstler/künstler210.jpg') ,
            require('./../../assets/photos/künstler/künstler211.jpg') ,
            require('./../../assets/photos/künstler/künstler212.jpg') ,
            require('./../../assets/photos/künstler/künstler213.jpg') ,
            require('./../../assets/photos/künstler/künstler214.jpg') ,
            require('./../../assets/photos/künstler/künstler215.jpg') ,
            require('./../../assets/photos/künstler/künstler216.jpg') ,
            require('./../../assets/photos/künstler/künstler217.jpg') ,
            require('./../../assets/photos/künstler/künstler218.jpg') ,
            require('./../../assets/photos/künstler/künstler219.jpg') ,
            require('./../../assets/photos/künstler/künstler220.jpg') ,
            require('./../../assets/photos/künstler/künstler221.jpg') ,
            require('./../../assets/photos/künstler/künstler222.jpg') ,
            require('./../../assets/photos/künstler/künstler223.jpg') ,
            require('./../../assets/photos/künstler/künstler224.jpg') ,
            require('./../../assets/photos/künstler/künstler225.jpg') ,
            require('./../../assets/photos/künstler/künstler226.jpg') ,
            require('./../../assets/photos/künstler/künstler227.jpg') ,
            require('./../../assets/photos/künstler/künstler228.jpg') ,
            require('./../../assets/photos/künstler/künstler229.jpg') ,
            require('./../../assets/photos/künstler/künstler230.jpg') ,
            require('./../../assets/photos/künstler/künstler231.jpg') ,
            require('./../../assets/photos/künstler/künstler232.jpg') ,
            require('./../../assets/photos/künstler/künstler233.jpg') ,
            require('./../../assets/photos/künstler/künstler234.jpg') ,
            require('./../../assets/photos/künstler/künstler235.jpg') ,
            require('./../../assets/photos/künstler/künstler236.jpg') ,
            require('./../../assets/photos/künstler/künstler237.jpg') ,
            require('./../../assets/photos/künstler/künstler238.jpg') ,
            require('./../../assets/photos/künstler/künstler239.jpg') ,
            require('./../../assets/photos/künstler/künstler240.jpg') ,
            require('./../../assets/photos/künstler/künstler241.jpg') ,
            require('./../../assets/photos/künstler/künstler242.jpg') ,
            require('./../../assets/photos/künstler/künstler243.jpg') ,
            require('./../../assets/photos/künstler/künstler244.jpg') ,
            require('./../../assets/photos/künstler/künstler245.jpg') ,
            require('./../../assets/photos/künstler/künstler246.jpg') ,
            require('./../../assets/photos/künstler/künstler247.jpg') ,
            require('./../../assets/photos/künstler/künstler248.jpg') ,
            require('./../../assets/photos/künstler/künstler249.jpg') ,
            require('./../../assets/photos/künstler/künstler250.jpg') ,
            require('./../../assets/photos/künstler/künstler251.jpg') ,
            require('./../../assets/photos/künstler/künstler252.jpg') ,
            require('./../../assets/photos/künstler/künstler253.jpg') ,
            require('./../../assets/photos/künstler/künstler254.jpg') ,
            require('./../../assets/photos/künstler/künstler255.jpg') ,
        ],
    index: null
        })

    }

</script>



<style>

     @import './../../assets/styles/galerie.css';

</style>